# Generated by Django 4.1.6 on 2023-02-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INFP', 'INFP'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('INTJ', 'INTJ'), ('ENTJ', 'ENTJ'), ('INFJ', 'INFJ'), ('ENFP', 'ENFP'), ('INTP', 'INTP'), ('ENFJ', 'ENFJ')], max_length=16, null=True),
        ),
    ]
