# Generated by Django 4.1.6 on 2023-02-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('ISTP', 'ISTP'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ENFJ', 'ENFJ'), ('INFP', 'INFP'), ('ESFJ', 'ESFJ'), ('ISTJ', 'ISTJ')], max_length=16, null=True),
        ),
    ]
