# Generated by Django 4.1.6 on 2023-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTP', 'ISTP'), ('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ'), ('ENFP', 'ENFP'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ENTJ', 'ENTJ'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ESFP', 'ESFP'), ('INFP', 'INFP'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('ESFJ', 'ESFJ'), ('ENTP', 'ENTP')], max_length=16, null=True),
        ),
    ]
