# Generated by Django 4.1.6 on 2023-02-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTP', 'ISTP'), ('INFJ', 'INFJ'), ('ISFP', 'ISFP'), ('ENFP', 'ENFP'), ('ESTJ', 'ESTJ'), ('INTJ', 'INTJ'), ('INFP', 'INFP'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('ISFJ', 'ISFJ'), ('INTP', 'INTP'), ('ENFJ', 'ENFJ'), ('ESTP', 'ESTP'), ('ENTP', 'ENTP'), ('ESFP', 'ESFP'), ('ISTJ', 'ISTJ')], max_length=16, null=True),
        ),
    ]
