# Generated by Django 4.1.6 on 2023-02-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFJ', 'ENFJ'), ('ESTP', 'ESTP'), ('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('ENTP', 'ENTP'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ISTJ', 'ISTJ'), ('INFP', 'INFP'), ('INTJ', 'INTJ'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ENFP', 'ENFP'), ('ISTP', 'ISTP'), ('ESFP', 'ESFP'), ('ISFP', 'ISFP')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='닉네임'),
        ),
    ]
