# Generated by Django 4.1.6 on 2023-02-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('INTP', 'INTP'), ('ENFJ', 'ENFJ'), ('ISTJ', 'ISTJ'), ('ESTP', 'ESTP'), ('INFP', 'INFP'), ('ISTP', 'ISTP'), ('ENFP', 'ENFP'), ('ISFP', 'ISFP'), ('ENTP', 'ENTP'), ('ISFJ', 'ISFJ'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('INTJ', 'INTJ')], max_length=16, null=True),
        ),
    ]
