# Generated by Django 3.2.18 on 2023-02-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTJ', 'ISTJ'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ'), ('INTJ', 'INTJ'), ('INFP', 'INFP'), ('ISTP', 'ISTP'), ('INTP', 'INTP'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ENTJ', 'ENTJ'), ('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP')], max_length=16, null=True),
        ),
    ]
