# Generated by Django 4.1.6 on 2023-02-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_mbti_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISFP', 'ISFP'), ('INFP', 'INFP'), ('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ'), ('ESTP', 'ESTP'), ('INFJ', 'INFJ'), ('INTP', 'INTP'), ('ISTP', 'ISTP'), ('ESFP', 'ESFP'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('ISTJ', 'ISTJ'), ('ENTJ', 'ENTJ'), ('ENFJ', 'ENFJ'), ('INTJ', 'INTJ'), ('ESTJ', 'ESTJ')], max_length=16, null=True),
        ),
    ]
