# Generated by Django 3.2.18 on 2023-02-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTP', 'INTP'), ('INFP', 'INFP'), ('ESFP', 'ESFP'), ('ISTJ', 'ISTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('INFJ', 'INFJ'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('ISTP', 'ISTP'), ('ESFJ', 'ESFJ')], max_length=16, null=True),
        ),
    ]
