# Generated by Django 4.1.6 on 2023-02-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFP', 'ESFP'), ('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('ESFJ', 'ESFJ'), ('ISTP', 'ISTP'), ('ENFJ', 'ENFJ'), ('ENTP', 'ENTP'), ('ISTJ', 'ISTJ'), ('ESTJ', 'ESTJ'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ENFP', 'ENFP'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ISFJ', 'ISFJ'), ('ENTJ', 'ENTJ')], max_length=16, null=True),
        ),
    ]
