# Generated by Django 3.2.18 on 2023-02-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTP', 'ISTP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('INTP', 'INTP'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('ESFP', 'ESFP'), ('INFJ', 'INFJ'), ('ESTP', 'ESTP')], max_length=16, null=True),
        ),
    ]
