# Generated by Django 4.1.6 on 2023-02-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ESTP', 'ESTP'), ('ESFJ', 'ESFJ'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('ENFP', 'ENFP'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ISTP', 'ISTP'), ('INTP', 'INTP'), ('INFP', 'INFP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ENFJ', 'ENFJ')], max_length=16, null=True),
        ),
    ]
