# Generated by Django 3.2.18 on 2023-02-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ENFP', 'ENFP'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('INFP', 'INFP'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('ENFJ', 'ENFJ'), ('ISTJ', 'ISTJ'), ('INFJ', 'INFJ'), ('ENTP', 'ENTP'), ('ISTP', 'ISTP')], max_length=16, null=True),
        ),
    ]
