# Generated by Django 4.1.6 on 2023-02-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_gender_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ESTP', 'ESTP'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('ENFJ', 'ENFJ'), ('ISTP', 'ISTP'), ('INFP', 'INFP'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ')], max_length=16, null=True),
        ),
    ]
