# Generated by Django 4.1.6 on 2023-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_gender_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTP', 'ENTP'), ('INFP', 'INFP'), ('INTP', 'INTP'), ('ESTP', 'ESTP'), ('INTJ', 'INTJ'), ('ENFJ', 'ENFJ'), ('ESFP', 'ESFP'), ('ENFP', 'ENFP'), ('INFJ', 'INFJ'), ('ISFP', 'ISFP'), ('ESFJ', 'ESFJ'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ESTJ', 'ESTJ'), ('ENTJ', 'ENTJ'), ('ISFJ', 'ISFJ')], max_length=16, null=True),
        ),
    ]
