# Generated by Django 4.1.6 on 2023-02-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_gender_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('ESFP', 'ESFP'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('INFJ', 'INFJ'), ('ENTP', 'ENTP'), ('INTP', 'INTP'), ('ISTP', 'ISTP'), ('ESFJ', 'ESFJ'), ('INFP', 'INFP'), ('ENFP', 'ENFP'), ('ENTJ', 'ENTJ'), ('ISFJ', 'ISFJ')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
