# Generated by Django 4.1.6 on 2023-02-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISFP', 'ISFP'), ('INFP', 'INFP'), ('ENTJ', 'ENTJ'), ('INTJ', 'INTJ'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP'), ('ESTP', 'ESTP'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ISTP', 'ISTP'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('ISTJ', 'ISTJ'), ('ENFJ', 'ENFJ'), ('INFJ', 'INFJ')], max_length=16, null=True),
        ),
    ]
