# Generated by Django 4.1.6 on 2023-02-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('ISTP', 'ISTP'), ('ESFP', 'ESFP'), ('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('INTP', 'INTP'), ('ENTP', 'ENTP'), ('ESFJ', 'ESFJ')], max_length=16, null=True),
        ),
    ]
