# Generated by Django 3.2.18 on 2023-02-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230223_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ESFJ', 'ESFJ'), ('ENTP', 'ENTP'), ('ENTJ', 'ENTJ'), ('ISTJ', 'ISTJ'), ('INFJ', 'INFJ'), ('ENFP', 'ENFP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ESTJ', 'ESTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('INFP', 'INFP'), ('ESFP', 'ESFP')], max_length=16, null=True),
        ),
    ]
