# Generated by Django 4.1.6 on 2023-02-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_gender_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('INFP', 'INFP'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('INFJ', 'INFJ'), ('ENTP', 'ENTP'), ('ISTP', 'ISTP'), ('ENFJ', 'ENFJ'), ('INTP', 'INTP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ENTJ', 'ENTJ'), ('ESFJ', 'ESFJ'), ('INTJ', 'INTJ')], max_length=16, null=True),
        ),
    ]
