<<<<<<< HEAD
# Generated by Django 3.2.18 on 2023-02-23 00:26
=======
# Generated by Django 4.1.6 on 2023-02-23 23:20
>>>>>>> b9d1b9a196711b6665ad3091a392fd33a8c11c07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('account', '0005_alter_profile_mbti'),
=======
        ('account', '0005_alter_profile_gender_alter_profile_mbti'),
>>>>>>> b9d1b9a196711b6665ad3091a392fd33a8c11c07
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
<<<<<<< HEAD
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('INTP', 'INTP')], max_length=16, null=True),
=======
            field=models.CharField(choices=[('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('INFP', 'INFP'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('INFJ', 'INFJ'), ('ENTP', 'ENTP'), ('ISTP', 'ISTP'), ('ENFJ', 'ENFJ'), ('INTP', 'INTP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ENTJ', 'ENTJ'), ('ESFJ', 'ESFJ'), ('INTJ', 'INTJ')], max_length=16, null=True),
>>>>>>> b9d1b9a196711b6665ad3091a392fd33a8c11c07
        ),
    ]
