# Generated by Django 4.1.6 on 2023-02-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_gender_alter_profile_mbti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFP', 'ESFP'), ('ISFP', 'ISFP'), ('ENFP', 'ENFP'), ('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ'), ('ENFJ', 'ENFJ'), ('INFP', 'INFP'), ('ISFJ', 'ISFJ'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ENTP', 'ENTP'), ('ESTP', 'ESTP'), ('INTJ', 'INTJ'), ('ISTP', 'ISTP')], max_length=16, null=True),
        ),
    ]
