# Generated by Django 3.2.18 on 2023-02-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('INTP', 'INTP')], max_length=16, null=True),
        ),
    ]
