# Generated by Django 3.2.18 on 2023-02-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_gender_alter_profile_mbti'),
        ('account', '0006_alter_profile_mbti'),
    ]

    operations = [
    ]
