# Generated by Django 4.1.6 on 2023-02-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFP', 'ESFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('ISFJ', 'ISFJ'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ISTJ', 'ISTJ'), ('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ISTP', 'ISTP'), ('INFJ', 'INFJ'), ('ENFJ', 'ENFJ'), ('ESTP', 'ESTP'), ('ENFP', 'ENFP')], max_length=16, null=True),
        ),
    ]
