# Generated by Django 4.1.6 on 2023-02-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('ENFP', 'ENFP'), ('ISTP', 'ISTP'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ENTP', 'ENTP'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('INTJ', 'INTJ'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ')], max_length=16, null=True),
        ),
    ]
