# Generated by Django 4.1.6 on 2023-02-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_gender_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFP', 'ESFP'), ('ISTP', 'ISTP'), ('INTP', 'INTP'), ('ISFP', 'ISFP'), ('ESFJ', 'ESFJ'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('INTJ', 'INTJ'), ('ISTJ', 'ISTJ'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ')], max_length=16, null=True),
        ),
    ]
