# Generated by Django 3.2.18 on 2023-02-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20230224_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('ESFP', 'ESFP'), ('ENTP', 'ENTP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ISFP', 'ISFP'), ('ENFJ', 'ENFJ'), ('ISFJ', 'ISFJ'), ('ESTP', 'ESTP')], max_length=16, null=True),
        ),
    ]
