# Generated by Django 4.1.6 on 2023-02-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_gender_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTJ', 'ENTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ESFJ', 'ESFJ'), ('ESTP', 'ESTP'), ('ISTJ', 'ISTJ'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('INTP', 'INTP'), ('INTJ', 'INTJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('INFP', 'INFP'), ('INFJ', 'INFJ'), ('ISFP', 'ISFP'), ('ENFJ', 'ENFJ')], max_length=16, null=True),
        ),
    ]
