# Generated by Django 3.2.18 on 2023-02-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20230223_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('ESFJ', 'ESFJ'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('INTJ', 'INTJ'), ('ESFP', 'ESFP')], max_length=16, null=True),
        ),
    ]
