# Generated by Django 4.1.6 on 2023-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTJ', 'ISTJ'), ('ENTP', 'ENTP'), ('INTJ', 'INTJ'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ESFJ', 'ESFJ'), ('ISFP', 'ISFP'), ('ISTP', 'ISTP'), ('INTP', 'INTP'), ('ESFP', 'ESFP'), ('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('ENFJ', 'ENFJ'), ('INFP', 'INFP')], max_length=16, null=True),
        ),
    ]
