# Generated by Django 3.2.18 on 2023-02-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20230223_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ENTP', 'ENTP'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('ENFP', 'ENFP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ISTP', 'ISTP'), ('INFP', 'INFP'), ('ISTJ', 'ISTJ'), ('ENFJ', 'ENFJ')], max_length=16, null=True),
        ),
    ]
