# Generated by Django 4.1.6 on 2023-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INFJ', 'INFJ'), ('ENFP', 'ENFP'), ('ESFJ', 'ESFJ'), ('ENTP', 'ENTP'), ('INTJ', 'INTJ'), ('ISTJ', 'ISTJ'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('ISTP', 'ISTP'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ISFJ', 'ISFJ')], max_length=16, null=True),
        ),
    ]
