# Generated by Django 3.2.18 on 2023-02-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INFP', 'INFP'), ('ISTJ', 'ISTJ'), ('ESTP', 'ESTP'), ('ENTP', 'ENTP'), ('ESFP', 'ESFP'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ENFP', 'ENFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP')], max_length=16, null=True),
        ),
    ]
