# Generated by Django 3.2.18 on 2023-02-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20230224_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTP', 'ISTP'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ESTJ', 'ESTJ'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('INFP', 'INFP'), ('ESFJ', 'ESFJ')], max_length=16, null=True),
        ),
    ]
