# Generated by Django 4.1.6 on 2023-02-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_gender_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('INFP', 'INFP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('INTP', 'INTP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('ESTJ', 'ESTJ'), ('ISTP', 'ISTP'), ('ESTP', 'ESTP')], max_length=16, null=True),
        ),
    ]
