# Generated by Django 3.2.18 on 2023-02-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20230223_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('ISTJ', 'ISTJ'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISFJ', 'ISFJ'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('ISTP', 'ISTP'), ('INTP', 'INTP'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP')], max_length=16, null=True),
        ),
    ]
