# Generated by Django 3.2.18 on 2023-02-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20230223_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFJ', 'ENFJ'), ('INTP', 'INTP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('ENFP', 'ENFP'), ('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('ISFJ', 'ISFJ'), ('INTJ', 'INTJ'), ('ENTP', 'ENTP'), ('ENTJ', 'ENTJ'), ('ESTP', 'ESTP')], max_length=16, null=True),
        ),
    ]
