# Generated by Django 4.1.6 on 2023-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('ENFJ', 'ENFJ'), ('ESTP', 'ESTP'), ('INTP', 'INTP'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('ENFP', 'ENFP'), ('ISTP', 'ISTP'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('INTJ', 'INTJ'), ('ISTJ', 'ISTJ'), ('ESTJ', 'ESTJ'), ('INFP', 'INFP'), ('INFJ', 'INFJ')], max_length=16, null=True),
        ),
    ]
