# Generated by Django 4.1.6 on 2023-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('ISFJ', 'ISFJ'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP'), ('ISTJ', 'ISTJ'), ('ENTP', 'ENTP'), ('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('ENFJ', 'ENFJ'), ('INTJ', 'INTJ'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ESFJ', 'ESFJ')], max_length=16, null=True),
        ),
    ]
