# Generated by Django 3.2.18 on 2023-02-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTJ', 'ENTJ'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('ENFJ', 'ENFJ'), ('INTJ', 'INTJ'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP'), ('ISTP', 'ISTP'), ('INTP', 'INTP'), ('INFP', 'INFP'), ('ISFP', 'ISFP'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ')], max_length=16, null=True),
        ),
    ]
