# Generated by Django 3.2.18 on 2023-02-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20230223_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('INFP', 'INFP'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP'), ('INTJ', 'INTJ'), ('ISTJ', 'ISTJ')], max_length=16, null=True),
        ),
    ]
