# Generated by Django 3.2.18 on 2023-02-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20230224_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTP', 'ISTP'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ENTJ', 'ENTJ'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('ISFP', 'ISFP'), ('INFP', 'INFP'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('ESTJ', 'ESTJ')], max_length=16, null=True),
        ),
    ]
