# Generated by Django 3.2.18 on 2023-02-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESTJ', 'ESTJ'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('ESTP', 'ESTP'), ('ISTP', 'ISTP'), ('INTP', 'INTP'), ('INFP', 'INFP'), ('ENFP', 'ENFP'), ('ESFP', 'ESFP'), ('ENTJ', 'ENTJ'), ('ISTJ', 'ISTJ'), ('ENFJ', 'ENFJ'), ('INTJ', 'INTJ'), ('ESFJ', 'ESFJ'), ('ISFP', 'ISFP'), ('ENTP', 'ENTP')], max_length=16, null=True),
        ),
    ]
