# Generated by Django 3.2.18 on 2023-02-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ENFP', 'ENFP'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('ISTP', 'ISTP'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ'), ('ESFP', 'ESFP'), ('INTP', 'INTP'), ('INFP', 'INFP'), ('ENTJ', 'ENTJ')], max_length=16, null=True),
        ),
    ]
