# Generated by Django 3.2.18 on 2023-02-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFP', 'ENFP'), ('ENTJ', 'ENTJ'), ('ESFJ', 'ESFJ'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('ESFP', 'ESFP'), ('ISFJ', 'ISFJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ'), ('ENFJ', 'ENFJ'), ('ISTP', 'ISTP'), ('INFP', 'INFP'), ('ENTP', 'ENTP')], max_length=16, null=True),
        ),
    ]
