# Generated by Django 3.2.18 on 2023-02-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTJ', 'ENTJ'), ('ESFJ', 'ESFJ'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFP', 'ISFP'), ('ENFJ', 'ENFJ'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ISFJ', 'ISFJ'), ('ISTP', 'ISTP'), ('ESFP', 'ESFP')], max_length=16, null=True),
        ),
    ]
