# Generated by Django 3.2.18 on 2023-02-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20230224_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ENFJ', 'ENFJ'), ('ISTP', 'ISTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ISFP', 'ISFP'), ('ENTJ', 'ENTJ'), ('INTJ', 'INTJ'), ('ESFP', 'ESFP'), ('INTP', 'INTP'), ('ISTJ', 'ISTJ'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ')], max_length=16, null=True),
        ),
    ]
