# Generated by Django 3.2.18 on 2023-02-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20230224_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTJ', 'ISTJ'), ('ENFJ', 'ENFJ'), ('ESTJ', 'ESTJ'), ('ISFJ', 'ISFJ'), ('ENTJ', 'ENTJ'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ESFJ', 'ESFJ'), ('ESTP', 'ESTP'), ('ENFP', 'ENFP'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('INFP', 'INFP'), ('ESFP', 'ESFP'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ')], max_length=16, null=True),
        ),
    ]
