# Generated by Django 3.2.18 on 2023-02-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('INTP', 'INTP'), ('ESTJ', 'ESTJ'), ('INFP', 'INFP'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('ENTJ', 'ENTJ'), ('ESFJ', 'ESFJ')], max_length=16, null=True),
        ),
    ]
