# Generated by Django 3.2.18 on 2023-02-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('INTP', 'INTP'), ('INFP', 'INFP'), ('ENTJ', 'ENTJ'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('INTJ', 'INTJ'), ('ISTP', 'ISTP')], max_length=16, null=True),
        ),
    ]
