# Generated by Django 3.2.18 on 2023-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20230224_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('ENTP', 'ENTP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('INFP', 'INFP'), ('ISTJ', 'ISTJ'), ('ESTJ', 'ESTJ')], max_length=16, null=True),
        ),
    ]
