# Generated by Django 3.2.18 on 2023-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INFJ', 'INFJ'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('ISFJ', 'ISFJ'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ESFJ', 'ESFJ'), ('INFP', 'INFP'), ('ISTP', 'ISTP')], max_length=16, null=True),
        ),
    ]
