# Generated by Django 3.2.18 on 2023-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('ENFJ', 'ENFJ'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('ENFP', 'ENFP'), ('ESFJ', 'ESFJ'), ('ISTJ', 'ISTJ'), ('INFP', 'INFP'), ('ISFP', 'ISFP'), ('ENTJ', 'ENTJ'), ('ISFJ', 'ISFJ'), ('ENTP', 'ENTP'), ('ISTP', 'ISTP'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('INTP', 'INTP')], max_length=16, null=True),
        ),
    ]
