# Generated by Django 3.2.18 on 2023-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20230224_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESTP', 'ESTP'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('ISTP', 'ISTP'), ('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('INFJ', 'INFJ'), ('ENTJ', 'ENTJ'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('INTP', 'INTP')], max_length=16, null=True),
        ),
    ]
