# Generated by Django 3.2.18 on 2023-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20230224_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('INFP', 'INFP'), ('ESFJ', 'ESFJ'), ('ESTJ', 'ESTJ'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ENFJ', 'ENFJ'), ('ISTJ', 'ISTJ'), ('ENTP', 'ENTP'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP')], max_length=16, null=True),
        ),
    ]
