# Generated by Django 3.2.18 on 2023-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20230224_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESTJ', 'ESTJ'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('ISFJ', 'ISFJ'), ('ESFJ', 'ESFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ENTP', 'ENTP'), ('INTJ', 'INTJ'), ('ENTJ', 'ENTJ'), ('ISTP', 'ISTP')], max_length=16, null=True),
        ),
    ]
