# Generated by Django 3.2.18 on 2023-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20230224_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('ISTP', 'ISTP'), ('ESFJ', 'ESFJ'), ('ESTP', 'ESTP'), ('ISFJ', 'ISFJ'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('INTP', 'INTP'), ('ISFP', 'ISFP')], max_length=16, null=True),
        ),
    ]
