# Generated by Django 3.2.18 on 2023-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ESFP', 'ESFP'), ('INFJ', 'INFJ'), ('ISTP', 'ISTP'), ('INTJ', 'INTJ'), ('ISFJ', 'ISFJ'), ('INFP', 'INFP')], max_length=16, null=True),
        ),
    ]
