# Generated by Django 3.2.18 on 2023-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTP', 'ENTP'), ('ENTJ', 'ENTJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ESTP', 'ESTP'), ('INFP', 'INFP'), ('INTP', 'INTP')], max_length=16, null=True),
        ),
    ]
