# Generated by Django 3.2.18 on 2023-02-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20230224_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('ENTJ', 'ENTJ'), ('ESFJ', 'ESFJ'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ENFJ', 'ENFJ'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('ISTP', 'ISTP'), ('ESFP', 'ESFP'), ('ISTJ', 'ISTJ')], max_length=16, null=True),
        ),
    ]
