# Generated by Django 3.2.18 on 2023-02-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('ENTP', 'ENTP'), ('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('ISTP', 'ISTP'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('ENFJ', 'ENFJ'), ('ESFJ', 'ESFJ'), ('ESTP', 'ESTP'), ('ENTJ', 'ENTJ')], max_length=16, null=True),
        ),
    ]
