# Generated by Django 3.2.18 on 2023-02-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ENFP', 'ENFP'), ('INFP', 'INFP'), ('ENTJ', 'ENTJ'), ('ISTP', 'ISTP'), ('ISTJ', 'ISTJ'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ')], max_length=16, null=True),
        ),
    ]
