# Generated by Django 3.2.18 on 2023-02-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_auto_20230224_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ'), ('INFP', 'INFP'), ('ISFP', 'ISFP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP')], max_length=16, null=True),
        ),
    ]
