# Generated by Django 3.2.18 on 2023-02-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_auto_20230224_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ENTJ', 'ENTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ISTP', 'ISTP'), ('ENFP', 'ENFP'), ('ESFP', 'ESFP'), ('ISFP', 'ISFP'), ('ESFJ', 'ESFJ'), ('ENTP', 'ENTP'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ')], max_length=16, null=True),
        ),
    ]
