# Generated by Django 3.2.18 on 2023-02-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INFP', 'INFP'), ('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('ENFP', 'ENFP'), ('ESTJ', 'ESTJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ENTP', 'ENTP'), ('ESFJ', 'ESFJ'), ('ENTJ', 'ENTJ')], max_length=16, null=True),
        ),
    ]
