# Generated by Django 3.2.17 on 2023-02-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISTP', 'ISTP'), ('INTJ', 'INTJ'), ('ENTJ', 'ENTJ'), ('ENFJ', 'ENFJ'), ('ESTP', 'ESTP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('ESTJ', 'ESTJ'), ('INFJ', 'INFJ'), ('INTP', 'INTP'), ('INFP', 'INFP'), ('ESFJ', 'ESFJ'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('ESFP', 'ESFP')], max_length=16, null=True),
        ),
    ]
