# Generated by Django 3.2.17 on 2023-02-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ESFP', 'ESFP'), ('ISFJ', 'ISFJ'), ('ESTP', 'ESTP'), ('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ENTP', 'ENTP'), ('INTP', 'INTP'), ('ESFJ', 'ESFJ'), ('INTJ', 'INTJ')], max_length=16, null=True),
        ),
    ]
