# Generated by Django 3.2.17 on 2023-02-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20230224_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTJ', 'ENTJ'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP')], max_length=16, null=True),
        ),
    ]
