# Generated by Django 3.2.17 on 2023-02-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20230224_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INFJ', 'INFJ'), ('ESTP', 'ESTP'), ('ISTJ', 'ISTJ'), ('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('INTJ', 'INTJ'), ('INFP', 'INFP'), ('ISFP', 'ISFP'), ('ISTP', 'ISTP'), ('INTP', 'INTP'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP')], max_length=16, null=True),
        ),
    ]
