# Generated by Django 4.1.6 on 2023-02-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_mbti'),
        ('account', '0056_alter_profile_mbti'),
    ]

    operations = [
    ]
