# Generated by Django 4.1.6 on 2023-02-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_merge_0002_alter_profile_mbti_0056_alter_profile_mbti'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='drink',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favfood',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hometown',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='live',
            field=models.CharField(choices=[('N', '무'), ('Y', '유')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timetable',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTP', 'INTP'), ('ESFP', 'ESFP'), ('ENTP', 'ENTP'), ('ESFJ', 'ESFJ'), ('ESTJ', 'ESTJ'), ('ISFP', 'ISFP'), ('ISTP', 'ISTP'), ('ENTJ', 'ENTJ'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('INTJ', 'INTJ'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('ISTJ', 'ISTJ')], max_length=16, null=True),
        ),
    ]
