# Generated by Django 3.2.18 on 2023-02-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_profile_drink_profile_favfood_profile_hometown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='live',
            field=models.CharField(choices=[('Y', '유'), ('N', '무')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('INTP', 'INTP'), ('ISFJ', 'ISFJ'), ('ENTJ', 'ENTJ'), ('INFP', 'INFP'), ('ESFJ', 'ESFJ'), ('ENFP', 'ENFP'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('ISTP', 'ISTP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ'), ('ENFJ', 'ENFJ')], max_length=16, null=True),
        ),
    ]
