# Generated by Django 3.2.18 on 2023-02-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='live',
            field=models.CharField(choices=[('N', '무'), ('Y', '유')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ENFJ', 'ENFJ'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ESTJ', 'ESTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('INFP', 'INFP'), ('ENTP', 'ENTP'), ('ISTJ', 'ISTJ'), ('ESTP', 'ESTP')], max_length=16, null=True),
        ),
    ]
