# Generated by Django 3.2.18 on 2023-02-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_auto_20230224_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='live',
            field=models.CharField(choices=[('N', '무'), ('Y', '유')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFP', 'ENFP'), ('INTJ', 'INTJ'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ISFJ', 'ISFJ'), ('ISTJ', 'ISTJ'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('ISFP', 'ISFP'), ('ISTP', 'ISTP'), ('INFP', 'INFP'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP')], max_length=16, null=True),
        ),
    ]
