# Generated by Django 4.1.7 on 2023-02-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_auto_20230224_0614'),
        ('account', '0060_auto_20230224_2220'),
    ]

    operations = [
    ]
