# Generated by Django 4.1.5 on 2023-02-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_auto_20230225_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFP', 'ENFP'), ('INTP', 'INTP'), ('ESFJ', 'ESFJ'), ('INFP', 'INFP'), ('ISTP', 'ISTP'), ('INTJ', 'INTJ'), ('ENTJ', 'ENTJ'), ('ESTP', 'ESTP'), ('ISFJ', 'ISFJ'), ('ENTP', 'ENTP'), ('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('ENFJ', 'ENFJ')], max_length=16, null=True),
        ),
    ]
