# Generated by Django 3.2.18 on 2023-02-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_auto_20230225_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='live',
            field=models.CharField(choices=[('Y', '유'), ('N', '무'), ('None', 'None')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFP', 'ENFP'), ('INTP', 'INTP'), ('ESTJ', 'ESTJ'), ('ISFJ', 'ISFJ'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ISTJ', 'ISTJ'), ('ESTP', 'ESTP'), ('ESFJ', 'ESFJ'), ('ISTP', 'ISTP'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('INTJ', 'INTJ')], max_length=16, null=True),
        ),
    ]
