# Generated by Django 3.2.18 on 2023-02-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_auto_20230225_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENTJ', 'ENTJ'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ESTJ', 'ESTJ')], max_length=16, null=True),
        ),
    ]
