# Generated by Django 3.2.18 on 2023-02-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_auto_20230225_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='live',
            field=models.CharField(choices=[('N', '무'), ('Y', '유'), ('None', 'None')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ISFP', 'ISFP'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ISTP', 'ISTP'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('ENFJ', 'ENFJ'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('INTP', 'INTP'), ('ENTP', 'ENTP'), ('ESFJ', 'ESFJ')], max_length=16, null=True),
        ),
    ]
