# Generated by Django 3.2.18 on 2023-02-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_auto_20230225_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ENFP', 'ENFP'), ('ENFJ', 'ENFJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('INTJ', 'INTJ'), ('ESTP', 'ESTP'), ('INFP', 'INFP'), ('ENTJ', 'ENTJ'), ('ESFP', 'ESFP'), ('INTP', 'INTP'), ('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('ISTJ', 'ISTJ'), ('ENTP', 'ENTP'), ('ESTJ', 'ESTJ')], max_length=16, null=True),
        ),
    ]
