# Generated by Django 3.2.18 on 2023-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='live',
            field=models.CharField(choices=[('N', '무'), ('None', 'None'), ('Y', '유')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('ENFJ', 'ENFJ'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('ISTP', 'ISTP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ENTJ', 'ENTJ'), ('ISTJ', 'ISTJ'), ('ESTP', 'ESTP')], max_length=16, null=True),
        ),
    ]
