# Generated by Django 3.2.18 on 2023-02-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_auto_20230224_1811'),
        ('account', '0063_alter_profile_mbti'),
        ('account', '0069_auto_20230225_0834'),
    ]

    operations = [
    ]
