# Generated by Django 4.1.6 on 2023-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_merge_20230225_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='live',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
