# Generated by Django 4.1.6 on 2023-02-24 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolveQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('solve_num', models.IntegerField(default=0)),
                ('quiz_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quesmodel')),
            ],
        ),
    ]
